name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    name: ${{ matrix.env.CI_NAME }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - {CI_NAME: Clang-Format,
             OS_NAME: ubuntu,
             OS_CODE_NAME: bionic,
             ROS_DISTRO: melodic,
             ROS_REPO: main,
             ROSDEP_SKIP_KEYS: "bullet3 fcl",
             CLANG_FORMAT_CHECK: file,
             CLANG_FORMAT_VERSION: 8,
             DOCKER_IMAGE: "rosindustrial/tesseract:melodic"}
          - {CI_NAME: Clang-Tidy,
             OS_NAME: ubuntu,
             OS_CODE_NAME: bionic,
             ROS_DISTRO: melodic,
             ROS_REPO: main,
             UPSTREAM_WORKSPACE: 'github:swri-robotics/descartes_light#master github:Jmeyer1292/opw_kinematics#master github:ros-industrial-consortium/trajopt_ros#feature/CommandLanguage github:ros-industrial-consortium/tesseract#feature/CommandLanguage github:ethz-adrl/ifopt#master github:ros-industrial/cmake_common_scripts#master',
             ROSDEP_SKIP_KEYS: "bullet3 cmake_common_scripts fcl iwyu",
             DOCKER_IMAGE: "rosindustrial/tesseract:melodic",
             CCACHE_DIR: "/home/runner/work/tesseract_ros/tesseract_ros/Clang-Tidy/.ccache",
             NOT_TEST_BUILD: true,
             UPSTREAM_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug",
             TARGET_CMAKE_ARGS: "-DTESSERACT_ENABLE_CLANG_TIDY=ON -DTESSERACT_ENABLE_TESTING=ON"}
          - {CI_NAME: Bionic-Build,
             OS_NAME: ubuntu,
             OS_CODE_NAME: bionic,
             ROS_DISTRO: melodic,
             ROS_REPO: main,
             UPSTREAM_WORKSPACE: 'github:swri-robotics/descartes_light#master github:Jmeyer1292/opw_kinematics#master github:ros-industrial-consortium/trajopt_ros#feature/CommandLanguage github:ros-industrial-consortium/tesseract#feature/CommandLanguage github:ethz-adrl/ifopt#master github:ros-industrial/cmake_common_scripts#master',
             ROSDEP_SKIP_KEYS: "bullet3 cmake_common_scripts fcl iwyu",
             DOCKER_IMAGE: "rosindustrial/tesseract:melodic",
             PARALLEL_TESTS: false,
             CCACHE_DIR: "/home/runner/work/tesseract_ros/tesseract_ros/Bionic-Build/.ccache",
             UPSTREAM_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Release",
             TARGET_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug"}
          - {CI_NAME: Xenial-Build,
             OS_NAME: ubuntu,
             OS_CODE_NAME: xenial,
             ROS_DISTRO: kinetic,
             ROS_REPO: main,
             UPSTREAM_WORKSPACE: 'github:swri-robotics/descartes_light#master github:Jmeyer1292/opw_kinematics#master github:ros-industrial-consortium/trajopt_ros#feature/CommandLanguage github:ros-industrial-consortium/tesseract#feature/CommandLanguage github:ethz-adrl/ifopt#master github:ros-industrial/cmake_common_scripts#master',
             ROSDEP_SKIP_KEYS: "benchmark bullet3 cmake_common_scripts fcl iwyu",
             DOCKER_IMAGE: "rosindustrial/tesseract:kinetic",
             PARALLEL_TESTS: false,
             CCACHE_DIR: "/home/runner/work/tesseract_ros/tesseract_ros/Xenial-Build/.ccache",
             UPSTREAM_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Release",
             TARGET_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=14"}
    steps:
      - uses: actions/checkout@v1

      - name: Free Disk Space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: ccache cache files
        uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.env.CI_NAME }}/.ccache
          key: ${{ matrix.env.CI_NAME }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ matrix.env.CI_NAME }}-ccache-

      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
